UNAME=$(shell uname)

ifeq ($(UNAME), Linux)
include Makefile.linux
else ifeq ($(UNAME), Darwin)
include Makefile.osx
endif

NAME=ssf
VERSION=v1
BUILD=$(shell git log --pretty=oneline | wc -l | sed 's/ //g')
SHA1=$(shell git rev-parse -q HEAD)
FULLNAME=$(NAME)\ $(VERSION).$(BUILD)

.PHONY: all FORCE clean

all: ssf libssf.$(LIB_EXT) ssf_cairo libssfcairo.$(LIB_EXT)

ssf: ssf.o ssf_sdl.o version.o
	$(CC) $(FLAGS) $^ -o $@ $(SDL2_LINK_FLAGS)

libssf.$(LIB_EXT): ssf.o version.o
	$(CC) $(FLAGS) -shared $^ -o $@

ssf_cairo: ssf.o ssf_cairo.o ssf_cairo_sdl.o version.o
	$(CC) $(FLAGS) $^ -o $@ $(SDL2_LINK_FLAGS) $(CAIRO_LINK_FLAGS)

libssfcairo.$(LIB_EXT): ssf.o ssf_cairo.o version.o
	$(CC) $(FLAGS) -shared $^ -o $@ $(CAIRO_LINK_FLAGS)

version.c: FORCE
	echo "/* Autogenerated by Makefile */" > $@.tmp
	echo "char gGitSha1[] = \"$(SHA1)\";" >> $@.tmp
	echo "char gVersion[] = \"$(VERSION).$(BUILD)\";" >> $@.tmp
	cmp -s $@.tmp $@ || mv $@.tmp $@
	rm -f $@.tmp

%.o: %.c *.c
	$(CC) $(FLAGS) -c $< -o $@ $(SDL2_LINK_FLAGS) $(CAIRO_LINK_FLAGS)

clean:
	rm -f *.o ssf libssf.$(LIB_EXT) ssf_cairo libssfcairo.$(LIB_EXT)
